Repository GSG-G11/e-commerce-team-2, pull requests merged in 2022-04, with the labels that each got.

#2 add basic folder structure
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  README.md
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/index.js
  package-lock.json
  package.json
  products.json
  server/app.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/index.js
Labels: Done

#8 add edit product feature
  server/app.js
  server/controllers/editProduct.js
  server/database/config/build.sql
  server/database/queries/editProduct.js
  server/routes.js
Labels: Awaiting Review

#10 add product
  server/controllers/addProduct.js
  server/controllers/editProduct.js
  server/database/queries/addProductQuery.js
  server/database/queries/editProductQuery.js
  server/routes.js
  server/utils/customizedError.js
Labels: Done

#11 6 delete prpduct
  .env.example
  server/app.js
  server/controllers/addProduct.js
  server/controllers/deleteProduct.js
  server/controllers/editProduct.js
  server/controllers/index.js
  server/database/config/build.sql
  server/database/queries/deleteProductQuery.js
  server/database/queries/index.js
  server/routes.js
Labels: Awaiting Review

#14 7 get product
  package-lock.json
  server/controllers/getAllProducts.js
  server/controllers/getProduct.js
  server/controllers/index.js
  server/database/queries/getAllProducts.js
  server/database/queries/getProduct.js
  server/database/queries/index.js
  server/routes.js
Labels: Awaiting Review

#16 Create landing Component
  client/public/assets/landing-img.png
  client/src/App.js
  client/src/Components/Button/Button.css
  client/src/Components/Landing/Landing.css
  client/src/Components/Landing/Landing.jsx
Labels: Awaiting Review

#19 header component
  client/src/App.js
  client/src/Components/Button/Button.css
  client/src/Components/Header/Header.css
  client/src/Components/Header/Header.jsx
  package-lock.json
Labels: Awaiting Review

#21 18 products component
  client/src/App.css
  client/src/App.js
  client/src/Components/Header/Header.css
  client/src/Components/Products/ProductCard/ProductCard.css
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Products/Products.css
  client/src/Components/Products/Products.jsx
Labels: Awaiting Review

#25 add cart component
  client/src/App.js
  client/src/Components/Cart/Cart.css
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Products/ProductCard/ProductCard.css
  client/src/Components/Products/Products.jsx
Labels: Awaiting Review

#26 add seller page component
  client/src/App.js
  client/src/Components/Cart/Cart.css
  client/src/Components/Seller/Seller.css
  client/src/Components/Seller/Seller.jsx
Labels: Awaiting Review

#27 20 log in user
  client/src/Components/Button/Button.css
  client/src/Components/Input/Input.css
  client/src/Components/Input/Input.jsx
  client/src/Components/Landing/Landing.jsx
  client/src/Components/LogInForm/LogInForm.css
  client/src/Components/LogInForm/LogInForm.jsx
Labels: Awaiting Review

#28 22 product details
  client/package-lock.json
  client/src/Components/ProductDetails/ProductDetails.css
  client/src/Components/ProductDetails/ProductDetails.jsx
Labels: Awaiting Review

#30 29 add prduct form
  client/src/Components/AddProductForm/AddProductForm.css
  client/src/Components/AddProductForm/AddProductForm.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Landing/Landing.jsx
  client/src/Components/Select/Select.css
  client/src/Components/Select/Select.jsx
Labels: Awaiting Review

#32 Filter price & category & search by name1
  client/src/App.js
  client/src/Components/Header/Header.css
  client/src/Components/Header/Header.jsx
  client/src/Components/Products/ProductCard/ProductCard.css
  client/src/Components/Select/Select.jsx
Labels: Awaiting Review

#33 fix nav
  client/src/App.js
  client/src/Components/Header/Header.css
  client/src/Components/Header/Header.jsx
  client/src/Components/Landing/Landing.css
  client/src/Components/LogInForm/LogInForm.css
  client/src/Components/Select/Select.css
Labels: Awaiting Review

#35 change landing component from class to function
  client/src/App.js
  client/src/Components/Landing/Landing.jsx
Labels: Awaiting Review

#38 fix card height
  client/src/App.js
  client/src/Components/Header/Header.css
  client/src/Components/Products/ProductCard/ProductCard.css
Labels: Awaiting Review

#40 add routes
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/Components/AddProductForm/AddProductForm.jsx
  client/src/Components/Cart/Cart.css
  client/src/Components/Header/Header.css
  client/src/Components/Header/Header.jsx
  client/src/Components/Landing/Landing.jsx
  client/src/Components/LogInForm/LogInForm.jsx
  client/src/Components/ProductDetails/ProductDetails.css
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Products/Products.jsx
  client/src/Components/Seller/Seller.css
  client/src/Components/Seller/Seller.jsx
  client/src/index.js
Labels: Done

#43 39 routes
  client/src/App.js
  client/src/Components/Header/Header.css
  client/src/Components/Header/Header.jsx
  client/src/Components/Products/ProductCard/ProductCard.css
  client/src/Components/Products/Products.css
  client/src/Components/Products/Products.jsx
  server/database/config/build.sql
Labels: Done

#50 handle get product to get prodcut details from database and display i…
  client/package-lock.json
  client/src/App.js
  client/src/Components/Button/Button.jsx
  client/src/Components/ProductDetails/ProductDetails.css
  client/src/Components/ProductDetails/ProductDetails.jsx
  package-lock.json
  server/controllers/getProduct.js
Labels: Awaiting Review

#51 get data from localStorge and render it in cart page
  client/package-lock.json
  client/public/index.html
  client/src/App.js
  client/src/Components/Cart/Cart.jsx
  client/src/Components/ProductDetails/ProductDetails.jsx
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Products/Products.jsx
Labels: Awaiting Review

#53 delete product and confirm deleting
  client/src/App.js
  client/src/Components/AddProductForm/AddProductForm.css
  client/src/Components/AddProductForm/AddProductForm.jsx
  client/src/Components/ConfirmedDeleting/ConfirmedDeleting.jsx
  client/src/Components/LogInForm/LogInForm.css
  client/src/Components/LogInForm/LogInForm.jsx
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Products/Products.jsx
  client/src/Components/Seller/Seller.jsx
Labels: Done

#54 52 delete products from cart
  client/src/App.js
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Products/Products.jsx
Labels: Done

#57 56 filter products
  client/src/App.js
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Select/Select.jsx
Labels: Awaiting Review

#59 58 get products from an api
  client/src/App.js
  client/src/Components/Header/Header.jsx
  client/src/Components/Products/ProductCard/ProductCard.jsx
  package-lock.json
  package.json
  server/database/config/build.sql
  server/index.js
Labels: Awaiting Review, Done, backend

#61 filter products in sellar page
  client/src/App.js
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Seller/Seller.jsx
Labels: Awaiting Review

#64 fix welcome container & product card responsive on small screens
  client/src/Components/Landing/Landing.css
  client/src/Components/Products/ProductCard/ProductCard.css
  client/src/Components/Products/Products.css
Labels: Awaiting Review

#65 Edit filter response
  client/public/assets/404-error.png
  client/public/assets/oops.png
  client/src/App.js
  client/src/Components/NotFound/NotFound.jsx
  client/src/Components/NotFound/NotFoundPage.css
  client/src/Components/Products/Products.css
  client/src/Components/Products/Products.jsx
  client/src/Components/footer/Footer.css
  client/src/Components/footer/Footer.jsx
  server/index.js
Labels: Done

#67 66 prepare heroku deploy
  client/package.json
  client/src/App.js
  client/src/Components/AddProductForm/AddProductForm.jsx
  client/src/Components/ProductDetails/ProductDetails.jsx
  client/src/Components/Products/ProductCard/ProductCard.jsx
  server/database/config/connection.js
Labels: Done

#70 create readme
  README.md
Labels: Done

#80 62 fix styles
  .vscode/launch.json
  client/src/App.js
  client/src/Components/AddProductForm/AddProductForm.jsx
  client/src/Components/Cart/Cart.jsx
  client/src/Components/Header/Header.css
  client/src/Components/Landing/Landing.css
  client/src/Components/Landing/Landing.jsx
  client/src/Components/NotFound/NotFoundPage.css
  client/src/Components/Products/ProductCard/ProductCard.jsx
  client/src/Components/Products/Products.jsx
  server/database/config/build.sql
  server/index.js
Labels: Done

#81 fix responsive in header
  client/src/Components/Header/Header.css
Labels: Done
